# Numpyを使う練習

In [1]:
import numpy as np

## 配列

In [2]:
np_list = np.array([1, 2, 3])
np_list

array([1, 2, 3])

### ブロードキャスト
配列の全要素に対して計算が行われること

In [3]:
a = np.array([1, 2, 3])
a * 3

array([3, 6, 9])

In [4]:
a + 3

array([4, 5, 6])

## 行列

In [5]:
np_list = np.array([[1, 2, 3], [2, 3, 4], [3, 4, 5]])
np_list

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

### 行列計算

In [6]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

array1
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
array1 + array2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [8]:
array1 = np.array([1, 2, 3])
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [9]:
array1 + array2

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

## Indexing

In [10]:
ndarray = np.array([[1, 2], [3, 4], [5, 6]])
print(ndarray)

[[1 2]
 [3 4]
 [5 6]]


In [11]:
print(ndarray[1, 0])
print(ndarray[0, 1])

3
2


In [12]:
print(ndarray[0])

[1 2]


In [13]:
print(ndarray[0, 1])

2


In [14]:
ndarray = np.array([[[111, 112, 113], [121, 122, 123], [131, 132, 133]], [[211, 212, 213], [221, 222, 223], [231, 232, 233]], [[311, 312, 313], [321, 322, 323], [331, 332, 333]]])
ndarray

array([[[111, 112, 113],
        [121, 122, 123],
        [131, 132, 133]],

       [[211, 212, 213],
        [221, 222, 223],
        [231, 232, 233]],

       [[311, 312, 313],
        [321, 322, 323],
        [331, 332, 333]]])

In [15]:
print(ndarray[0])

[[111 112 113]
 [121 122 123]
 [131 132 133]]


In [16]:
print(ndarray[0, 1])

[121 122 123]


In [17]:
print(ndarray[0, 1, 1])

122


## Slicing

In [18]:
ndarray

array([[[111, 112, 113],
        [121, 122, 123],
        [131, 132, 133]],

       [[211, 212, 213],
        [221, 222, 223],
        [231, 232, 233]],

       [[311, 312, 313],
        [321, 322, 323],
        [331, 332, 333]]])

In [19]:
ndarray[:, :, :]

array([[[111, 112, 113],
        [121, 122, 123],
        [131, 132, 133]],

       [[211, 212, 213],
        [221, 222, 223],
        [231, 232, 233]],

       [[311, 312, 313],
        [321, 322, 323],
        [331, 332, 333]]])

In [20]:
ndarray[:, :, 1:]

array([[[112, 113],
        [122, 123],
        [132, 133]],

       [[212, 213],
        [222, 223],
        [232, 233]],

       [[312, 313],
        [322, 323],
        [332, 333]]])

In [21]:
ndarray[1:, 0:1, 1:2]

array([[[212]],

       [[312]]])

In [22]:
ndarray[1, 0, 1]

212

In [23]:
ndarray[2, 0, 1]

312

## 様々なndarrayを作る

### np.arange()

np.arange([start,] stop[, step])  
start以上stop未満の値をstepずつ増加させた値のarrayを作成する

In [24]:
array = np.arange(1, 20, 3)
print(array)

[ 1  4  7 10 13 16 19]


In [25]:
array = np.arange(1, 20)
print(array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


### np.linspace()

np.linspace(start, stop, num=50)  
startからstopまでの値をnum等分した値のarrayを作成する

In [26]:
array = np.linspace(1, 20, 10)
print(array)

[ 1.          3.11111111  5.22222222  7.33333333  9.44444444 11.55555556
 13.66666667 15.77777778 17.88888889 20.        ]


## np.zeros(shape)

0行列を作成する

In [27]:
shape = (2, 3, 5)
zeros = np.zeros(shape)
print(zeros)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


## np.ones(shape)

1行列を作成する

In [28]:
shape = (2, 3, 5)
ones_array_1 = np.ones(shape)
ones_array_2 = np.ones(4)
 
print(ones_array_1)
print(ones_array_2)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
[1. 1. 1. 1.]


## np.eye(N)

N x Nの単位行列を作成する

In [29]:
array = np.eye(3)
print(array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [30]:
array = np.eye(3, 5)
print(array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


## np.random.rand()

0 ~ 1からランダムな数字で行列を作ることができます．引数を入れなければfloatが，引数の数によって返されるarrayの次元が変わります．

In [31]:
random_float = np.random.rand()
random_1d = np.random.rand(3)
random_2d = np.random.rand(3, 4)
 
print('random_float: {}\n'.format(random_float))
print('random_1d: {}\n'.format(random_1d))
print('random_2d: {}\n'.format(random_2d))

random_float: 0.47615032628054044

random_1d: [0.86941313 0.41849412 0.3233649 ]

random_2d: [[0.64327513 0.75970448 0.01993438 0.18630771]
 [0.72419757 0.47396898 0.47338958 0.33772968]
 [0.2326488  0.21894422 0.46449998 0.02978769]]



## np.random.randn()

In [32]:
random_float = np.random.randn()
random_1d = np.random.randn(3)
random_2d = np.random.randn(3, 4)
 
print('random_float: {}\n'.format(random_float))
print('random_1d: {}\n'.format(random_1d))
print('random_2d: {}\n'.format(random_2d))

random_float: -0.4542140655793378

random_1d: [ 0.43770428  0.69487478 -0.45790612]

random_2d: [[-1.59715833 -0.86026809 -0.9075856   0.67048456]
 [-0.46400087 -0.90830174 -0.75252117  2.25061756]
 [ 1.33862768 -1.59284841 -0.59869011 -1.11445141]]



## np.random.randint(low[, high] [, size])

low以上hith未満のsizeに指定したndarrayを返す

In [33]:
array = np.random.randint(10, 50, size=(2, 4, 3))
print(array)

[[[29 43 18]
  [11 39 35]
  [24 41 24]
  [39 36 43]]

 [[28 35 37]
  [46 23 14]
  [49 10 29]
  [23 43 26]]]


## .reshape(shape)

変更前と変更後で要素数は一致していないといけません

In [34]:
array = np.arange(0, 10)
print('array:\n{}'.format(array))
new_shape = (2, 5)
reshaped_array = array.reshape(new_shape)
print('reshaped array:\n{} '.format(reshaped_array))
print("reshaped array's is:\n{} ".format(reshaped_array.shape))
print('original array is NOT changed:\n{}'.format(array))

array:
[0 1 2 3 4 5 6 7 8 9]
reshaped array:
[[0 1 2 3 4]
 [5 6 7 8 9]] 
reshaped array's is:
(2, 5) 
original array is NOT changed:
[0 1 2 3 4 5 6 7 8 9]


## 要素の統計量を求める
統計量というのは、最大値、最小値、平均値、中央値、標準偏差などのデータの特徴を要約した値

In [35]:
normal_dist_mat = np.random.randn(5, 5)
print(normal_dist_mat)

[[ 0.27443421 -0.01324324 -0.92133031 -0.23385767  0.4896472 ]
 [-0.12779978  1.33566605  1.08426683  0.48119821 -1.81597497]
 [-1.26828858 -0.90447096 -0.10929102 -2.33114902 -0.01796317]
 [-1.31883491 -1.57539767 -2.52574527  0.27698011 -0.77181996]
 [-0.44673056 -0.12851918 -1.10388913 -0.87349143  0.10119352]]


### .max()と.argmax()

#### .max()
要素の最大値を取得する

In [36]:
print("max is")
print(normal_dist_mat.max())
print(np.max(normal_dist_mat))

max is
1.335666054419309
1.335666054419309


### .argmax()
最大値の要素を持つindexを返す

In [37]:
print("argmax is")
print(normal_dist_mat.argmax())
print(np.argmax(normal_dist_mat))

argmax is
6
6


In [38]:
normal_dist_mat.flatten()[24]

0.10119351958409042

.min()と.argmin()
最小値の用を持つindexを返す

#### .min()
要素の最小値を返す

In [39]:
print("min is")
print(normal_dist_mat.min())
print(np.min(normal_dist_mat))

min is
-2.525745272053774
-2.525745272053774


#### .argmin()
最小値の要素を持つindexを返す

In [40]:
print("argmin is")
print(normal_dist_mat.argmin())
print(np.argmin(normal_dist_mat))

argmin is
17
17


In [41]:
normal_dist_mat.flatten()[8]

0.4811982062071449

### .mean()
平均値を取得する

In [42]:
print("mean is")
print(normal_dist_mat.mean())
print(np.mean(normal_dist_mat))

mean is
-0.49777642802933
-0.49777642802933


### np.median(ndarray)
中央値を取得する

In [43]:
print("median is")
print(np.median(normal_dist_mat))

median is
-0.233857673854153


### .std()
標準偏差(standard deviation)を取得します

In [44]:
print("standard deviatin is")
print(normal_dist_mat.std())
print(np.std(normal_dist_mat))

standard deviatin is
0.9567357767151166
0.9567357767151166


## 数学でよく使う関数

### np.exp(ndarray)
ネイピア数(約2.718)

In [45]:
ndarray = np.linspace(-3, 3, 10)
expndarray = np.exp(ndarray)
print(ndarray)
print(expndarray)

[-3.         -2.33333333 -1.66666667 -1.         -0.33333333  0.33333333
  1.          1.66666667  2.33333333  3.        ]
[ 0.04978707  0.09697197  0.1888756   0.36787944  0.71653131  1.39561243
  2.71828183  5.29449005 10.3122585  20.08553692]


### np.log(ndarray)
np.exp()のlog版

In [49]:
ndarray = np.linspace(-3, 3, 10)
logndarray = np.log(ndarray)
print(ndarray)
print(logndarray)

[-3.         -2.33333333 -1.66666667 -1.         -0.33333333  0.33333333
  1.          1.66666667  2.33333333  3.        ]
nan


/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in log
  


### np.nanとnp.isnan()
nanとはNot-A-NumberのことでありNoneとは別物

In [51]:
print(expndarray[0])
print("nan == None?:{}".format(expndarray[0] is None))

0.049787068367863944
nan == None?:False


In [54]:
ndarray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'array is:\n{ndarray}')
print(f"ndarray's shape is:\n{ndarray.shape}")

array is:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndarray's shape is:
(3, 3)


## NumPy Arrayを保存する&読み込む

### np.save('ファイルバス', ndarray)

In [55]:
ndarray = np.array([
    [1, 2, 3, 4],
    [10, 20, 30, 40],
    [100, 200, 300, 400],
])
np.save('saved_numpy', ndarray)

### np.load('ファイルパス')

In [56]:
loaded_numpy = np.load('saved_numpy.npy')
loaded_numpy

array([[  1,   2,   3,   4],
       [ 10,  20,  30,  40],
       [100, 200, 300, 400]])

# メモ

In [58]:
c = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
np.sum(c)

21

In [60]:
np.sum(c, axis=1)

array([ 6, 15])

In [61]:
np.sum(c, axis=0)

array([5, 7, 9])