# Numpyを使う練習

In [ ]:
import numpy as np

## 配列

In [5]:
np_list = np.array([1, 2, 3])
np_list

array([1, 2, 3])

## 行列

In [6]:
np_list = np.array([[1, 2, 3], [2, 3, 4], [3, 4, 5]])
np_list

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

### 行列計算

In [8]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

array1
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
array1 + array2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [11]:
array1 = np.array([1, 2, 3])
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [12]:
array1 + array2

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

## Indexing

In [13]:
ndarray = np.array([[1, 2], [3, 4], [5, 6]])
print(ndarray)

[[1 2]
 [3 4]
 [5 6]]


In [17]:
print(ndarray[1, 0])
print(ndarray[0, 1])

3
2


In [18]:
print(ndarray[0])

[1 2]


In [19]:
print(ndarray[0, 1])

2


In [21]:
ndarray = np.array([[[111, 112, 113], [121, 122, 123], [131, 132, 133]], [[211, 212, 213], [221, 222, 223], [231, 232, 233]], [[311, 312, 313], [321, 322, 323], [331, 332, 333]]])
ndarray

array([[[111, 112, 113],
        [121, 122, 123],
        [131, 132, 133]],

       [[211, 212, 213],
        [221, 222, 223],
        [231, 232, 233]],

       [[311, 312, 313],
        [321, 322, 323],
        [331, 332, 333]]])

In [23]:
print(ndarray[0])

[[111 112 113]
 [121 122 123]
 [131 132 133]]


In [24]:
print(ndarray[0, 1])

[121 122 123]


In [25]:
print(ndarray[0, 1, 1])

122


## Slicing

In [26]:
ndarray

array([[[111, 112, 113],
        [121, 122, 123],
        [131, 132, 133]],

       [[211, 212, 213],
        [221, 222, 223],
        [231, 232, 233]],

       [[311, 312, 313],
        [321, 322, 323],
        [331, 332, 333]]])

In [28]:
ndarray[:, :, :]

array([[[111, 112, 113],
        [121, 122, 123],
        [131, 132, 133]],

       [[211, 212, 213],
        [221, 222, 223],
        [231, 232, 233]],

       [[311, 312, 313],
        [321, 322, 323],
        [331, 332, 333]]])

In [31]:
ndarray[:, :, 1:]

array([[[112, 113],
        [122, 123],
        [132, 133]],

       [[212, 213],
        [222, 223],
        [232, 233]],

       [[312, 313],
        [322, 323],
        [332, 333]]])

In [32]:
ndarray[1:, 0:1, 1:2]

array([[[212]],

       [[312]]])

In [34]:
ndarray[1, 0, 1]

212

In [35]:
ndarray[2, 0, 1]

312